# Generated by Django 2.0.1 on 2018-01-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CytogeneticAbnormality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormality', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FishTestComponentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_test_component', models.CharField(default='', max_length=32)),
                ('fish_test_component_percentage_value', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunophenotypeCytochemistryTestingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunophenotype_cytochemistry_percent_positive', models.CharField(default='', max_length=32)),
                ('immunophenotype_cytochemistry_testing_result', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MolecularAnalysisAbnormalityTestingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecular_analysis_abnormality_testing_percentage_value', models.CharField(default='', max_length=32)),
                ('molecular_analysis_abnormality_testing_result', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='acute_myeloid_leukemia_calgb_cytogenetics_risk_category',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='additional_studies',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='age_at_initial_pathologic_diagnosis',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='assessment_timepoint_category',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='atra_exposure',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='bcr_patient_barcode',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='bcr_patient_uuid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='cumulative_agent_total_dose',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytogenetic_abnormality_other',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytogenetic_analysis_performed_ind',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='day_of_form_completion',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='days_to_birth',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='days_to_death',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='days_to_initial_pathologic_diagnosis',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='days_to_last_followup',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='days_to_last_known_alive',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease_detection_molecular_analysis_method_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease_detection_molecular_analysis_method_type_other_text',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='drugs',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='eastern_cancer_oncology_group',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='fish_evaluation_performed_ind',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='fish_test_component_results',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='fluorescence_in_situ_hybrid_cytogenetics_metaphase_nucleus_result_count',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='fluorescence_in_situ_hybridization_abnormal_result_indicator',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='follow_ups',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='germline_testing_performed',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_of_neoadjuvant_treatment',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='hydroxyurea_administration_prior_registration_clinical_study_indicator',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='hydroxyurea_agent_administered_day_count',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='icd_10',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='icd_o_3_histology',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='icd_o_3_site',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='informed_consent_verified',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='initial_pathologic_diagnosis_method',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='karnofsky_performance_score',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_abnormal_lymphocyte_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_blast_cell_outcome_percentage_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_band_cell_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_basophil_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_blast_cell_outcome_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_cellularity_outcome_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_diff_not_reported_reason',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_lab_eosinophil_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_lymphocyte_outcome_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_metamyelocyte_result_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_myelocyte_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_neutrophil_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_prolymphocyte_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_promonocyte_count_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_bone_marrow_promyelocyte_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_hematocrit_outcome_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_hemoglobin_result_specified_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_leukocyte_result_unspecified_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_procedure_monocyte_result_percent_value',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='leukemia_french_american_british_morphology_code',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='leukemia_specimen_cell_source_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='molecular_analysis_abnormal_result_indicator',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='month_of_form_completion',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_dx',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='performance_status_scale_timing',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='person_history_leukemogenic_agent_other_exposure_text',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='person_history_nonmedical_leukemia_causing_agent_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='platelet_result_count',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='prior_hematologic_disorder_diagnosis_indicator',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='radiations',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='steroid_therapy_administered',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='tissue_source_site',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_dose_units',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='tumor_tissue_site',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='tumor_tissue_site_other',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='vital_status',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='year_of_form_completion',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='year_of_initial_pathologic_diagnosis',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytogenetic_abnormality',
            field=models.ManyToManyField(to='aml_app.CytogeneticAbnormality'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fish_test_component_result',
            field=models.ManyToManyField(to='aml_app.FishTestComponentResult'),
        ),
        migrations.AddField(
            model_name='patient',
            name='immunophenotype_cytochemistry_testing_result',
            field=models.ManyToManyField(to='aml_app.ImmunophenotypeCytochemistryTestingResult'),
        ),
        migrations.AddField(
            model_name='patient',
            name='molecular_analysis_abnormality_testing_result',
            field=models.ManyToManyField(to='aml_app.MolecularAnalysisAbnormalityTestingResult'),
        ),
    ]
